languageCode = "pt-BR"
title = "site do Felipe Rosa"
baseURL = "https://felpesrosa.github.io/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = ""
  codePenUser = "Heydon"
